### ISSUE TITLE
Frontend: Flaky test due to "cannot log after tests are done" error

### ISSUE THREAD

**Issue by omarkohl** [cleodora-forecasting/cleodora#290]
```bash
Cannot log after tests are done. Did you forget to wait for something async in your test?
    Attempted to log "Error getting config TypeError: Cannot read properties of null (reading '_location')
        at Window.get location [as location] (/home/runner/work/cleodora/cleodora/frontend/node_modules/jsdom/lib/jsdom/browser/Window.js:375:79)
        at FetchInterceptor.<anonymous> (/home/runner/work/cleodora/cleodora/frontend/node_modules/@mswjs/interceptors/src/interceptors/fetch/index.ts:50:22)
        at step (/home/runner/work/cleodora/cleodora/frontend/node_modules/@mswjs/interceptors/lib/interceptors/fetch/index.js:59:23)
        at Object.next (/home/runner/work/cleodora/cleodora/frontend/node_modules/@mswjs/interceptors/lib/interceptors/fetch/index.js:40:53)
        at fulfilled (/home/runner/work/cleodora/cleodora/frontend/node_modules/@mswjs/interceptors/lib/interceptors/fetch/index.js:31:58)
        at runNextTicks (node:internal/process/task_queues:61:5)
        at processImmediate (node:internal/timers:437:9)".

      36 |                  }
      37 |             )
    > 38 |             .catch(
         |               ^
      39 |                 (reason) => {
      40 |                     console.log("Error getting config", reason)
      41 |                 }

      at Window.get location [as location] (node_modules/jsdom/lib/jsdom/browser/Window.js:375:79)
      at FetchInterceptor.<anonymous> (node_modules/@mswjs/interceptors/src/interceptors/fetch/index.ts:50:22)
      at step (node_modules/@mswjs/interceptors/lib/interceptors/fetch/index.js:59:23)
      at Object.next (node_modules/@mswjs/interceptors/lib/interceptors/fetch/index.js:40:53)
      at fulfilled (node_modules/@mswjs/interceptors/lib/interceptors/fetch/index.js:31:58)
      at processImmediate (node:internal/timers:437:9)".
      at console.log (node_modules/react-scripts/node_modules/@jest/console/build/BufferedConsole.js:199:10)
      at src/Footer.tsx:38:15
```

It's probably some sort of race condition.

It happens from time to time e.g. here: https://github.com/cleodora-forecasting/cleodora/actions/runs/4294409786/jobs/7483394228

**Comment by omarkohl** [comment]
Issue has not been solved with the above commit. https://github.com/cleodora-forecasting/cleodora/actions/runs/4480272259/jobs/7875344833?pr=338

**Comment by omarkohl** [comment]
Seems to be the same issue http://tech.yipp.ca/reactjs/jest-react-useeffect-executed-test-log-tests-done-forget-wait-something-async-test/

**Comment by omarkohl** [comment]
Maybe related https://github.com/testing-library/react-testing-library/issues/667

**Comment by omarkohl** [comment]
Looking good so far after the latest commit. If there are no failures until the end of May in can be closed.

**Comment by omarkohl** [comment]
It might have become less frequent but the job is still failing https://github.com/cleodora-forecasting/cleodora/actions/runs/5070288233/jobs/9105115234?pr=501

**Comment by omarkohl** [comment]
Even after running the tests ~500 times locally it did not fail, but it is still failing in GitHub actions. The explanation for _that_ seems to be https://github.com/jestjs/jest/issues/11132 i.e. it only fails in CI but not locally.

**Comment by omarkohl** [comment]
Interesting comment, but the whole thread might be useful: https://github.com/jestjs/jest/issues/9324#issuecomment-1199457498

**Comment by omarkohl** [comment]
I am able to reproduce the issue locally with the following command. The error appears about every 10 executions.

```
cd frontend
npm run test -- --all --bail --ci --watchAll=false --runInBand
```
